[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "mega666"
version = "0.1.0"
description = "FH6 Auto Wheelspin"
requires-python = ">=3.10"
dependencies = [
    "rapidocr-onnxruntime>=1.2",
    "numpy>=1.24",
    "pywin32>=306",
    "psutil>=5.9",
    "colorama>=0.4.6",
    "rich>=13.7",
]
authors = [
  { name = "Hachiro"}
]

[project.scripts]
mega666 = "mega666.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
